### ISSUE TITLE
WALC 0.2.0 redirects to Google Chrome Update after a Whatsapp update today.

### ISSUE THREAD

**Issue by bkmo** [cstayyab/WALC#138]
I am being shown the Update Google Chrome page after getting a new WhatsApp update notice today. Using the new 0.2.0 appimage on arch linux KDE.

**Comment by tsjk** [comment]
I have the same. Would be nice to know how to revert the update.

**Comment by Zzombiee2361** [comment]
Ok this must be from the new electron-forge version, try using [the same version but compiled with electron-builder](https://drive.google.com/file/d/1_7Qdw47TBmQTL4Mt4cyVqBO2XZyKHgl3/view?usp=sharing). Works for me, and without the notification bug

**Comment by bkmo** [comment]
Yes, the electron-builder version does not ask for Chrome update.  Thanks

**Comment by tsjk** [comment]
If I click "update WhatsApp" it asks for Chrome update regardless. I take backups of my home directory quite often, and restoring ~/.config/walc made WALC usable again. Not clicking doesn't really help though, as restarting the app again puts it in a non-usable state. And, I'm using that electron-builder-version.

**Comment by tsjk** [comment]
Downgrading to 0.1.11 works well, then I can get past the "update WhatsApp". And, that version doesn't ask whether I want to exit when I explicitly click quit - which his nice. :)

**Comment by mauromol** [comment]
I still have this problem although using WALC 0.2.1 (from Snapcraft). Is it normal?

**Comment by cstayyab** [comment]
@mauromol Does it still say "Chrome 60+" or does it show some other version number?

**Comment by mauromol** [comment]
@cstayyab wow, it now works, I don't know why... I have just been keeping it closed since this morning and now it starts... :-\

I confirm this morning it said "Chrome 60+", and I also confirm that it was already updated to version 0.2.1 (I even closed it and reopened a couple of times to make sure that no snap update was still pending).
Perhaps some caching problem? Is there a way to try to "force" a refresh once the application is running? I tried the "old classics" F5 key, but it did nothing.

**Comment by cstayyab** [comment]
@mauromol If it was the caching problem then it probably was Snap being running in background (Some `snapd` mechanism i think) even after you closed it. You just need to check if WALC process is still in the memory and kill it.

**Comment by mauromol** [comment]
Oh, well, I just started today WALC and I get this again:

![image](https://user-images.githubusercontent.com/1742494/117426026-b6c4d080-af23-11eb-8eb0-100aea2a640c.png)

```
mauro@hppb ~ $ snap info walc
name:      walc
summary:   WALC - unofficial WhatsApp Linux Client
publisher: Muhammad Tayyab Sheikh (cstayyab)
store-url: https://snapcraft.io/walc
contact:   https://cstayyab.com/contact
license:   unset
description: |
  A WhatsApp Desktop client for Linux systems. This is an unofficial client. Use
  https://web.whatsapp.com for official web client as official desktop client for Linux does not
  exist.
  
  **Source Code:** https://github.com/cstayyab/WALC
  
  **AppImage(All Linux Distributions):** https://github.com/cstayyab/WALC/releases/latest
commands:
  - walc
snap-id:      WZrAWsHcPldM6nqlPpTg25X2NXXXnNA3
tracking:     latest/stable
refresh-date: 2 days ago, at 11:11 CEST
channels:
  latest/stable:    0.2.1 2021-05-04 (19) 69MB -
  latest/candidate: 0.2.1 2021-05-04 (19) 69MB -
  latest/beta:      0.2.1 2021-05-04 (19) 69MB -
  latest/edge:      0.2.1 2021-05-04 (19) 69MB -
installed:          0.2.1            (19) 69MB -
```

Closed WALC with the upper-right "x", confirmed closing the app, started WALC again and now it started correctly.

So it's like it's a "hit or miss" whenever I start WALC...

**Comment by tsjk** [comment]
There was a new update. Version 0.1.11-post got past it without any problems.

**Comment by mauromol** [comment]
@tsjk I still see version 0.2.1 (the one I'm using) as the latest one, both on Snapcraft and here on GitHub.

**Comment by Zzombiee2361** [comment]
@mauromol oh no, what language is that? We do have a mechanic to workaround this issue, but it checks if the string "Update Google Chrome" exists on the page. Since that string doesn't exists, the workaround never fires ¯\\\_(ツ)\_/¯

If anyone has a better way on detecting that update page, go on and open pull request or tell us here

**Comment by cstayyab** [comment]
@Zzombiee2361 I updated the `UserAgent` String after 0.2.1 release and as per my testing this page never even shows. Can you verify the latest code, so may be we can release a bug-fix release?

**Comment by mauromol** [comment]
@Zzombiee2361 it's Italian. What surprises me is that, as others already said, this problem never occurred with the old WALC version.

I find that searching for the string "Update Google Chrome" is a bit fragile. Perhaps looking at the HTML/CSS structure of that page would be a bit more robust, at least for as long as the Whatsapp web service doesn't change that page with something substantially different...

**Comment by Zzombiee2361** [comment]
@cstayyab alright I'll test it

@mauromol probably because of the user agent then. But there is some rare case where you need to unregister the service worker to get it working. When that happens, we need to check for that page, and we do need a reliable way to detect it.

Have you ever looked at the actual html? The classes are randomly generated lol, just using the structure would be too broad. Putting that dashboard icon is already a hack as it is.

**Comment by Torkin1** [comment]
> I find that searching for the string "Update Google Chrome" is a bit fragile.

Using a string translated in system locale could solve the issue, at least in most cases

**Comment by Zzombiee2361** [comment]
That's like putting even more hack for a problem caused by another hack. We need a sturdy solution

**Comment by mauromol** [comment]
Today I get this problem again. Tried to close/reopen WALC 3-4 times, but this time it seems not to fix the problem.

Still on 0.2.1, because I don't see new versions on snapcraft.

**Comment by mauromol** [comment]
Usually after some restart attempts, the issue gets fixed, but now it's from yesterday, after a Whatsapp update, that I can't use WALC anymore.

@Zzombiee2361 what about @cstayyab change suggested in https://github.com/cstayyab/WALC/issues/138#issuecomment-834236324?

Meanwhile is there any workaround to make WALC work again? i.e.: clear out some settings folder or such?
Thanks in advance.

**Comment by kotatsuman** [comment]
It happened to me too and I solved launching WALC twice (whithout closing it). While the first window I launched was still showing the Chrome update message, the second one was showing WhatsApp Web QR code ready to scan. Ubuntu Hirsute Hippo. Il 21 lug 2021 09:37, Mauro Molinari ***@***.***> ha scritto:
Usually after some restart attempts, the issue gets fixed, but now it's from yesterday, after a Whatsapp update, that I can't use WALC anymore.
@Zzombiee2361 what about @cstayyab change suggested in #138 (comment)?
Meanwhile is there any workaround to make WALC work again? i.e.: clear out some settings folder or such?
Thanks in advance.

**Comment by mauromol** [comment]
> It happened to me too and I solved launching WALC twice (whithout closing it). While the first window I launched was still showing the Chrome update message, the second one was showing WhatsApp Web QR code ready to scan. 

Worked here in Ubuntu 20.04 as well, thank you for the tip! Though, the second instance of WALC had all the application settings reset to their default value... For instance, I was using the dark theme, but the second instance started with the default theme. I don't know how this is supposed to work... Fortunately this is not an application that requires too much customisation 😉

**Comment by kotatsuman** [comment]
Glad it worked for you too. I have no idea about settings, since mine don't reset. I installed WALC using Snap, did you compile sources maybe? Il 23 lug 2021 11:28, Mauro Molinari ***@***.***> ha scritto:



It happened to me too and I solved launching WALC twice (whithout closing it). While the first window I launched was still showing the Chrome update message, the second one was showing WhatsApp Web QR code ready to scan.



Worked here in Ubuntu 20.04 as well, thank you for the tip! Though, the second instance of WALC had all the application settings reset to their default value... For instance, I was using the dark theme, but the second instance started with the default theme. I don't know how this is supposed to work... Fortunately this is not an application that requires too much customisation 😉

**Comment by mauromol** [comment]
> Glad it worked for you too. I have no idea about settings, since mine don't reset. I installed WALC using Snap, did you compile sources maybe?

No I didn't, I'm also using snap.

**Comment by mauromol** [comment]
@kotatsuman today it happened again and I fixed it again by launching a second WALC instance. I confirm it's seen as a totally new instance, hence it must be paired with the Whatsapp mobile app again, it's seen as a new connected device and settings are yet again reset.

Looking forward for an actual fix.
