### ISSUE TITLE
Microphone/Camera Not Found

### ISSUE THREAD

**Issue by AlwaysBeCalm** [cstayyab/WALC#28]
Hi
I'm Using Ubuntu 20.04 and I'm having a problem with the snap version, when I want to capture a photo or a video or record a voice message it says:
Camera Not Found
Microphone Not Found

![image](https://user-images.githubusercontent.com/54927528/81466331-7a0fad80-91d9-11ea-9c10-22fc10e6e49b.png)
![image](https://user-images.githubusercontent.com/54927528/81466338-8b58ba00-91d9-11ea-986e-7ade0fd82891.png)

It didn't show to me the allow message, but when I went to the web version or the appimage it worked.
Can it be solved

Thanks :rose: :ok_hand:

**Comment by cstayyab** [comment]
You need to give WALC permissions from Ubuntu App Store / Snap Store.

**Comment by AlwaysBeCalm** [comment]
Thanks for replying :rose: :rose: 
the recording works fine now.

Although I gave it all the premissions

![image](https://user-images.githubusercontent.com/54927528/81499470-8e84a080-92d4-11ea-8e1f-2d94d2b3e1aa.png)

but it still show me that the camera is not found, even after restarting the app many times. :sweat:

**Comment by salim-b** [comment]
> You need to give WALC permissions from Ubuntu App Store / Snap Store.

You can also do this on the terminal:

```sh
sudo snap connect walc:pulseaudio :pulseaudio
```

> but it still show me that the camera is not found, even after restarting the app many times. :sweat:

WALC doesn't implement the [`camera` interface]() yet. If it would, we could just enable it by

```sh
sudo snap connect walc:camera :camera
```

**Comment by cstayyab** [comment]
This has been fixed in the `master` branch. It will be released in next version. If you want to download now you can shift to Channel `edge` using `sudo snap refresh walc --channel=edge`
 
**Note:** *Channel edge may contain abrupt changes and may break WALC for you. Although Camera interface is automatically enabled according to [this post](https://forum.snapcraft.io/t/please-auto-connect-camera-interface-for-flock-chat-was-need-classic-confinement-to-get-camera-access-and-file-download/5534/12) on SnapCraft but if you still face issue with camera use the command specified in @salim-b [ccmment](https://github.com/cstayyab/WALC/issues/28#issuecomment-626703095)*

**Comment by AlwaysBeCalm** [comment]
@salim-b 
@cstayyab 

Thanks :rose:

**Comment by shahmir811** [comment]
Thanks alot @salim-b 

The following solution works for me:

`sudo snap connect walc:pulseaudio :pulseaudio`

**Comment by atorresbr** [comment]
> ```shell
> ```shell
> sudo snap connect walc:pulseaudio :pulseaudio
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

tnx

**Comment by atorresbr** [comment]
> 

thanks

**Comment by Zzombiee2361** [comment]
Please do note that the snap version is no longer updated
