### ISSUE TITLE
[Bug Report] When opening app while it's hidden in tray it won't show up

### ISSUE THREAD

**Issue by agustinmorantes** [cstayyab/WALC#57]
**Describe the bug**
When WALC is hidden in tray, if you try to reopen it from the GNOME app drawer or the dock, it does not open. Instead it shows the "Are you sure you want to exit?" prompt. When disabling the prompt from settings then clicking the app in the dock does not do absolutely anything. The only way to open it is through the tray icon.

**WALC Installation Type:** Both AppImage and Snap do the same

**To Reproduce**
1. Open WALC
2. Hide to tray (from tray icon or closing the window)
3. Open from the dock / app drawer in GNOME

**Expected behavior**
The window should just show up, like when clicking "Show WALC" on tray icon.

**Did you try closing and then opening it back?:** Yes, even tried reinstalling and using both versions

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Additional context**
Discord, for example, when hidden in tray shows up normally when trying to open from dock

**Comment by bjeanes** [comment]
I am also getting this, but additionally, the tray icon will often simply disappear, even though walc is still running (confirmed with `ps`).

Whether or not the tray icon is visible, the following error is received when trying to open WhatsApp from Dock:

![image](https://user-images.githubusercontent.com/2560/88468844-8a0f7180-cf2c-11ea-89d7-119a406720dc.png)

If the tray icon _is_ absent, the only thing I am able to do is `killall walc` and re-open from there.

Seems related to #56

**Comment by scottyd** [comment]
Me too. Just out of interest, this actually removes a lot of the non-system icons from my tray - until I restart the desktop environment. 

I am running Mint 20, Cinnamon desktop. So essentially at the moment, WALC is running, however I cannot see it and have the following icons from other running apps in my taskbar:

![image](https://user-images.githubusercontent.com/385170/89156264-b753c380-d5ad-11ea-93e4-e771cd0e63a8.png)

If I then click on the WALC app, it has the same exit message as @bjeanes above:

![image](https://user-images.githubusercontent.com/385170/89156337-dfdbbd80-d5ad-11ea-8597-890be3062a9b.png)

As soon as I click on the WALC app icon from the panel, even before the message, all my non-system apps have now removed from the taskbar:

![image](https://user-images.githubusercontent.com/385170/89156424-04379a00-d5ae-11ea-92b8-6b5205f986ab.png)

The only way to get them back, is to restart Cinnamon. A couple of other things: 
1. I do receive notifications and can open the window by clicking on one. 
2. It appears that WALC may open itself many times in the background on this error. 
3. This only happens when the "close to tray" option is selected. 

Happy to help out with logs, etc. if they will help. 

Thanks
S
